### PR TITLE
Add rational curve fit for sheen albedo

### PR DESCRIPTION
**Pull request by jstone-lucasfilm**

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
Here's a comparison of roughness wedges for the Standard Surface velvet material.

Sheen albedo table:
Velvet_SheenAlbedoTable

Sheen albedo curve fit:
Velvet_SheenAlbedoCurve

**Comment by jstone-lucasfilm** [comment]
Here's a comparison of sheen roughness wedges for the Standard Surface velvet material.

Sheen albedo table (16x16):
Velvet_SheenAlbedoTable

Sheen albedo curve:
Velvet_SheenAlbedoCurve

**Comment by jstone-lucasfilm** [comment]
For additional context, I'm thinking of this change as a first step along a path of improvements for sheen rendering, with the following ideas for future steps:

- Add ground truth rendering for sheen albedo (following the same Monte Carlo approach we currently use for GGX directional albedo).
- Add a run-time generated look-up texture for sheen albedo (as with GGX directional albedo).
- Refine our curve fit using this run-time generated data, which should be more accurate than the original hardcoded table.
- Add a shader generation switch for the sheen albedo rendering method (Monte Carlo, look-up texture, or curve fit).

**Review by niklasharrysson — APPROVED** [review]
This is an excellent change and a great plan for future steps. Thanks Jonathan!

**Pull request merged**
